# This compose file is intended to run backend tests in local
services:
  database:
    container_name: database
    restart: always
    image: postgres:16-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 10
      timeout: 5s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # TODO: Use env
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: backend
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=local-test
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
