services:
  db:
    container_name: db
    restart: always
    image: postgres:16-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg-isready', '-U', 'postgres']
    volumes:
      - ./postgres16:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # TODO: Use env
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: backend
    build: .
    restart: always
    env_file: .env
    networks:
      - internal_network
      - external_network
    ports:
      - 8000:8000
    depends_on:
      - db

networks:
  external_network:
  internal_network:
    internal: true
