# Generated by Django 5.0.6 on 2024-05-27 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeforcesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50, unique=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('max_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('participated_contests_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('problem_index', models.CharField(max_length=2)),
                ('programming_language', models.CharField(max_length=25)),
                ('submission_id', models.IntegerField(unique=True)),
                ('verdict', models.CharField(blank=True, choices=[('FL', 'Failed'), ('AC', 'Ok'), ('PT', 'Partial'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('PE', 'Presentation Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('ILE', 'Idleness Limit Exceeded'), ('SV', 'Security Violated'), ('CR', 'Crashed'), ('IPC', 'Input Preparation Crashed'), ('CH', 'Challenged'), ('SK', 'Skipped'), ('TE', 'Testing'), ('RJ', 'Rejected')], max_length=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforces.codeforcesuser')),
            ],
            options={
                'ordering': ['-submission_id'],
            },
        ),
    ]
