name: Django Testing

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pipx
        run: python -m pip install pipx

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Wait for PostgreSQL
        run: until pg_isready -h localhost -p 5432; do echo "Waiting for postgres..."; sleep 1; done

      - name: Run tests
        env:
          DATABASE_HOST: localhost
        run: poetry run pytest dashboard
